name: "Validations"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  Static-Analysis:
    name: "Static analysis"
    runs-on: ubuntu-24.04
    steps:
      - name: Bootstrap environment
        uses: anchore/go-make/.github/actions/bootstrap@latest

      - name: Run static analysis
        run: make static-analysis

  Unit-Test:
    name: "Unit tests"
    runs-on: ubuntu-24.04
    steps:
      - name: Bootstrap environment
        uses: anchore/go-make/.github/actions/bootstrap@latest

      - name: Run unit tests
        run: make unit
